"""initial schema

Revision ID: b5aac762889a
Revises: 
Create Date: 2026-08-20 20:17:54.451740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Columns use app.db.models.UtcDateTime, so generated migrations must be able
# to resolve it by name.
import app.db.models  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'b5aac762889a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', app.db.models.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('TRIAL', 'ACTIVE', 'PAST_DUE', 'SUSPENDED', name='ownerstatus', native_enum=False), nullable=False),
    sa.Column('plan_expires_at', app.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.Enum('STARS', 'ZARINPAL', 'PAYPAL', 'MANUAL_CARD', name='providerkind', native_enum=False), nullable=False),
    sa.Column('provider_config', sa.Text(), nullable=True),
    sa.Column('referral_code', sa.String(length=16), nullable=False),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.models.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.models.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['referred_by_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owners_referral_code'), ['referral_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_owners_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_owners_telegram_user_id'), ['telegram_user_id'], unique=True)

    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('created_at', app.db.models.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.models.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscribers_telegram_user_id'), ['telegram_user_id'], unique=True)

    op.create_table('managed_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('grace_days', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.models.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.models.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id', name='uq_channel_chat_id')
    )
    with op.batch_alter_table('managed_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_managed_channels_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_managed_channels_telegram_chat_id'), ['telegram_chat_id'], unique=False)

    op.create_table('platform_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('base_amount', sa.BigInteger(), nullable=False),
    sa.Column('unique_suffix', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', 'REFUNDED', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('paid_at', app.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.models.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.models.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_invoices_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_invoices_status'), ['status'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price_amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.models.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.models.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['managed_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_is_active'), ['is_active'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'GRACE', 'EXPIRED', 'CANCELLED', name='subscriptionstatus', native_enum=False), nullable=False),
    sa.Column('starts_at', app.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('expires_at', app.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_at', app.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('removed_at', app.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.models.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.models.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['managed_channels.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('ix_subscription_expiry_sweep', ['status', 'expires_at'], unique=False)
        batch_op.create_index('ix_subscription_member', ['channel_id', 'subscriber_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_subscriber_id'), ['subscriber_id'], unique=False)

    op.create_table('invite_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('used_at', app.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', app.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.models.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.models.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_links_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('STARS', 'ZARINPAL', 'PAYPAL', 'MANUAL_CARD', name='providerkind', native_enum=False), nullable=False),
    sa.Column('provider_ref', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', 'REFUNDED', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('confirmed_at', app.db.models.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.models.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.models.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_ref', name='uq_payment_provider_ref')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_subscription_id'), ['subscription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))

    op.drop_table('payments')
    with op.batch_alter_table('invite_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_links_subscription_id'))

    op.drop_table('invite_links')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_subscriber_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_channel_id'))
        batch_op.drop_index('ix_subscription_member')
        batch_op.drop_index('ix_subscription_expiry_sweep')

    op.drop_table('subscriptions')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_is_active'))
        batch_op.drop_index(batch_op.f('ix_plans_channel_id'))

    op.drop_table('plans')
    with op.batch_alter_table('platform_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_platform_invoices_owner_id'))

    op.drop_table('platform_invoices')
    with op.batch_alter_table('managed_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_managed_channels_telegram_chat_id'))
        batch_op.drop_index(batch_op.f('ix_managed_channels_owner_id'))

    op.drop_table('managed_channels')
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscribers_telegram_user_id'))

    op.drop_table('subscribers')
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owners_telegram_user_id'))
        batch_op.drop_index(batch_op.f('ix_owners_status'))
        batch_op.drop_index(batch_op.f('ix_owners_referral_code'))

    op.drop_table('owners')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
